### PR TITLE
setlocalversion: don't add commit hash

### PR DESCRIPTION
**Pull request by FraSharp**

### CODE REVIEW

**Comment by FraSharp** [comment]
@FraSharp aa

**Comment by blankaf** [comment]
@FraSharp Huh

**Comment by blankaf** [comment]
@FraSharp Tu bsdk hai

**Comment by FraSharp** [comment]
@blankaf no ur

**Comment by blankaf** [comment]
@FraSharp Send sex

**Comment by FraSharp** [comment]
@blankaf ok

**Comment by sashascurtu** [comment]
@blankaf nigger close this already

**Pull request closed without merging**
